name = "monoes-landing"
compatibility_date = "2025-04-17"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

routes = [
  { pattern = "monoes.me/*", zone_name = "monoes.me" },
  { pattern = "www.monoes.me/*", zone_name = "monoes.me" }
]
